### PR TITLE
Added functionality to switch user via a command line parameter

### PR DESCRIPTION
**Pull request by ignesco**
I am using this functionality to provide the posibility of Angel running as root looking after an Angel running as one or more less privileged users, e.g. user provided http end points sitting behind nginx on a multi user web server.

It can also be used just to run Angel as a less privileged user on startup.

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Is there a reason why you wouldn't add this to the config on a per-program basis? I've actually got a rewrite of Angel going and that's what I do there.

**Comment by ignesco** [comment]
The reason is this gives more autonomy to the restricted user. Each restricted user would own their own config file and would be free to author it as they required.  You would not want the initial Angel process (running as user 0) to spawn other Angel processes (also running as user 0) that read configuration files writable by restricted users, as these users could specify any process to run as any other user they wish by specifying that user in *their* config file.  This would be a security risk.

The only way this scenario can be satisfied is by ensuring that before the config file is opened the user switching has taken place.

**Comment by MichaelXavier** [comment]
I'm sorry but I still don't think I follow. You're saying you've got angel running as root, and then in your config you've got it starting other Angel processes running user-supplied configs right? What I'm saying is  in the config for your root angel, each sub-angel you've got you'd have something like `user = "jimmy"` in the config. Root angel as part of its forking process, first thing it will do is setuid/setgid on the process so its running limited. In my mind this seems better since *any* program could be run as a non-root user not just other angels. Am I missing something?

Here's an example in my rewrite, Seraph:

https://github.com/MichaelXavier/Seraph/blob/c971a6c9ed6391cec73b760e4271c6ea150f060e/src/Seraph/Process.hs#L134

It forks, sets uid/gid, working directory, fds for stdin/stdout/stderr, *then* runs the requested process.

**Comment by ignesco** [comment]
Hi Michael,

That approach would work if Angel forked each child process.  I looked to see if there was an obvious location in the master code branch where the child process is forked, but it seems to use createProcess directly without forking.  First it would need fork and then create the process.  Do you think modification of Angel at this scale would be acceptable for use in a production system?  Would you be happy for me to code this change and resubmit for approval? 
Thanks, Craig

**Comment by MichaelXavier** [comment]
This is starting to come back to me a bit. I'm pretty sure this original issue is what sparked my desire to rewrite angel, having to move away from createProcess and instead to a more manual sequence of commands. So the short answer is that I'd be fine with createProcess being swapped out for manual forking. I'm reasonably confident in the test suite. Feel free to borrow code from Seraph. Seraph employs a free monad as a middleman for testing purposes, but its a pretty thin layer over the low level calls.

**Comment by ignesco** [comment]
Please could you give me some background on the reason Angel.Data.getFile has to be wrapped with TChan pipes.  I might need to pass the stdout and stderr file paths to the forked process, but I cannot see the reason for the extra STM use.  Is it something to do with opening the files in Append mode or is there something else I am not aware of?  I would have thought that a call to open a file in append mode would be atomic anyway.

**Comment by ignesco** [comment]
Are you OK with me opening a new pull request for the new work I have done after following your recommendations? Thanks.

**Comment by MichaelXavier** [comment]
Whoops. Sorry I missed your first question. I don't know why the original author went with this design. I found it puzzling. As I'm sure you've done by now, feel free to move forward without that design.

And yes, a new PR would be great and feel free to close this one once you do so. You can also mention this one by id which should link them should we ever need to view the history again. Thanks!

**Comment by ignesco** [comment]
New pull request #39 contains the latest code for this functionality.  Thanks.

**Pull request closed without merging**
