### PR TITLE
attempt to fix issue #58

### PR DESCRIPTION
**Pull request by vwwv**
Tiny PR to fix issue 58

### CODE REVIEW

**Comment by MichaelXavier** [comment]
@vwwv have you tested this out and does it look like it works without disturbing any behavior not affected by the bug you're addressing?

**Comment by vwwv** [comment]
@MichaelXavier so I'm using angel on the stage of a project, I just patch it yesterday and it seems it is working fine so far, the issue is no longer there and at least within this project case, it seems there's no behavior changed.

I found that tearing down angel with `SIGTERM` did not kill as expected one of angel's processes in one case (it was still up and running after angel went down). But not sure why this happen, I _think_, it was not related to these changes.

**Comment by vwwv** [comment]
I can try it a bit longer and let you know once I'm more confident.

**Comment by vwwv** [comment]
It seems the issue is related to angel not finding out it needs to kill the process, some times it does, sometimes it doesn't. This doesn't seems to be related to this PR, though I'll double check it.

**Comment by vwwv** [comment]
It does introduce problems ... I'll try to find other ways

**Pull request closed without merging**
